### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by michelmelo** [micaelsouza/superplayer-playlist-dl#4]
Olá hoje apareceu outro erro :)

> /usr/local/lib/node_modules/superplayer-playlist-dl/index.js:4
> const fs = require('fs');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>     at node.js:814:3

**Comment by micaelsouza** [comment]
@michelmelo verifique a versão do nodejs que você está rodando, caso seja alguma versão antes da 4.x, tente atualizar o nodejs pra uma 4.x ou superior e execute novamente. Caso o problema continue, por favor reporte aqui.

**Comment by micaelsouza** [comment]
Já se passaram oito dias e como não houve mais relatos do problema, vou fechar esta issue julgando que o problema foi mesmo a versão do nodejs que estava abaixo da versão 4.x.

**Comment by michelmelo** [comment]
@micaelsouza ola desculpe, fiquei sem o mac e ainda estava de ferias :)
Bom era mesmo do nodejs. :) obrigado
