### ISSUE TITLE
Todas as músicas estão sendo baixadas em baixa qualidade

### ISSUE THREAD

**Issue by micaelsouza** [micaelsouza/superplayer-playlist-dl#5]

**Comment by michelmelo** [comment]
consegui perceber como alterar isso ?

**Comment by micaelsouza** [comment]
@michelmelo dei uma olhada rápida no problema e percebi que eles estão movendo os arquivos de alta qualidade para outro CDN e disponibilizando a URL apenas para usuários premium. Não fui a fundo no problema por falta de tempo.

**Comment by michelmelo** [comment]
ok, chegou a ter acesso ao um dos links do HD? se tiver um posso ajudar a corrigi isso

**Comment by micaelsouza** [comment]
Tenho sim, vou comentar aqui até amanhã.

**Comment by micaelsouza** [comment]
@michelmelo, como eu tinha dito, aqui está um link de uma das músicas em HD [https://content03.superplayer.fm/sme/2/e/676e7ff47e5fdd0e1fb1966805163f097e3e9168.mp3](https://content03.superplayer.fm/sme/2/e/676e7ff47e5fdd0e1fb1966805163f097e3e9168.mp3)

**Comment by michelmelo** [comment]
@micaelsouza ok, ja vi 
https://content01
https://content02
agora o 3 é novidade :) 
https://content03
vou te ajudar a resolver isso.

**Comment by michelmelo** [comment]
Bom, ate agora não vi uma forma de baixa em alta qualidade a nao ser que esteja logado como pago.

**Comment by micaelsouza** [comment]
Também foi a única forma que eu encontrei de baixar em alta qualidade, somente estando logado e sendo usuário premium. Vou fechrar essa issue até surgir outra forma de resolver ela já que, no momento, isso é meio inviável.
